import { Router } from "express";
import { sql } from "drizzle-orm";
import { z } from "zod";
import { requireAuth } from "../middleware/auth.js";
import { db } from "../db/client.js";

type Row=Record<string,any>;
export const agentRoleRequestsRouter=Router();
async function rows(query:any):Promise<Row[]>{const result=await db!.execute(query) as unknown as Row[]|{rows:Row[]};return Array.isArray(result)?result:result.rows;}
agentRoleRequestsRouter.get("/affiliations/role-requests",requireAuth,async(req,res)=>{if(!db)return res.json({data:[]});const data=await rows(sql`SELECT rr.id,rr.current_role,rr.requested_role,rr.status,rr.created_at,a.id agent_id,a.name agent_name,a.slug agent_slug FROM agent_role_requests rr JOIN agents a ON a.id=rr.agent_id WHERE rr.user_id=${req.auth!.subjectId} ORDER BY rr.created_at DESC`);return res.json({data:data.map(r=>({id:r.id,currentRole:r.current_role,requestedRole:r.requested_role,status:r.status,createdAt:r.created_at,agentId:r.agent_id,agentName:r.agent_name,agentSlug:r.agent_slug}))});});
agentRoleRequestsRouter.post("/affiliations/role-requests",requireAuth,async(req,res)=>{if(!db)return res.status(503).json({error:"Database unavailable"});const parsed=z.object({agentId:z.string().uuid(),requestedRole:z.string().trim().min(2).max(160)}).safeParse(req.body);if(!parsed.success)return res.status(400).json({error:"Choose an Agent and enter the role you want to request."});const affiliation=(await rows(sql`SELECT aa.agent_id,aa.role,a.name FROM agent_affiliations aa JOIN agents a ON a.id=aa.agent_id WHERE aa.agent_id=${parsed.data.agentId} AND aa.user_id=${req.auth!.subjectId} LIMIT 1`))[0];if(!affiliation)return res.status(403).json({error:"You must have an active affiliation with this Agent before requesting a role upgrade."});const pending=(await rows(sql`SELECT id FROM agent_role_requests WHERE agent_id=${parsed.data.agentId} AND user_id=${req.auth!.subjectId} AND status='pending' LIMIT 1`))[0];if(pending)return res.status(409).json({error:"A role upgrade request is already pending."});const created=(await rows(sql`INSERT INTO agent_role_requests(agent_id,user_id,current_role,requested_role,status) VALUES (${parsed.data.agentId},${req.auth!.subjectId},${affiliation.role},${parsed.data.requestedRole},'pending') RETURNING id,status,requested_role,created_at`))[0];return res.status(201).json({data:{...created,requestedRole:created.requested_role,createdAt:created.created_at}});});
agentRoleRequestsRouter.get("/affiliations/agent-role-requests",requireAuth,async(req,res)=>{if(!db)return res.json({data:[]});const agent=(await rows(sql`SELECT id FROM agents WHERE id=${req.auth!.subjectId} AND verified=true AND verification_status='approved' LIMIT 1`))[0];if(!agent)return res.status(403).json({error:"Only verified Agents can review role requests."});const data=await rows(sql`SELECT rr.id,rr.current_role,rr.requested_role,rr.status,rr.created_at,u.id user_id,u.name user_name,u.username FROM agent_role_requests rr JOIN users u ON u.id=rr.user_id WHERE rr.agent_id=${agent.id} AND rr.status='pending' ORDER BY rr.created_at ASC`);return res.json({data:data.map(r=>({id:r.id,currentRole:r.current_role,requestedRole:r.requested_role,status:r.status,createdAt:r.created_at,userId:r.user_id,userName:r.user_name,username:r.username}))});});
agentRoleRequestsRouter.post("/affiliations/agent-role-requests/:id/:decision",requireAuth,async(req,res)=>{if(!db)return res.status(503).json({error:"Database unavailable"});const decision=String(req.params.decision);if(decision!=="accept"&&decision!=="reject")return res.status(400).json({error:"Unknown decision."});const agent=(await rows(sql`SELECT id FROM agents WHERE id=${req.auth!.subjectId} AND verified=true AND verification_status='approved' LIMIT 1`))[0];if(!agent)return res.status(403).json({error:"Only verified Agents can review role requests."});const request=(await rows(sql`SELECT * FROM agent_role_requests WHERE id=${req.params.id} AND agent_id=${agent.id} AND status='pending' LIMIT 1`))[0];if(!request)return res.status(404).json({error:"Role request not found."});if(decision==='reject'){await db.execute(sql`UPDATE agent_role_requests SET status='rejected',updated_at=now() WHERE id=${request.id}`);return res.json({data:{status:'rejected'}});}await db.execute(sql`UPDATE agent_role_requests SET status='accepted',updated_at=now() WHERE id=${request.id}`);await db.execute(sql`UPDATE agent_affiliations SET role=${request.requested_role},verified_at=now() WHERE agent_id=${agent.id} AND user_id=${request.user_id}`);await db.execute(sql`INSERT INTO agent_affiliation_history(agent_id,user_id,role,event_type) VALUES (${agent.id},${request.user_id},${request.requested_role},'role_upgrade')`);return res.json({data:{status:'accepted',role:request.requested_role}});});
