import { Router } from "express";
import { randomUUID } from "node:crypto";
import { z } from "zod";
import { sql } from "drizzle-orm";
import { requireAuth } from "../middleware/auth.js";
import { db } from "../db/client.js";
import { postMedia, posts } from "../db/schema.js";
export const socialPostCreateRouter=Router();
socialPostCreateRouter.post("/posts",requireAuth,async(req,res)=>{const parsed=z.object({body:z.string().trim().min(1).max(5000),projectSlug:z.string().max(100).optional(),linkUrl:z.string().url().max(2000).nullable().optional(),media:z.array(z.object({path:z.string(),mimeType:z.string(),publicUrl:z.string().url().optional()})).max(10).default([])}).safeParse(req.body);if(!parsed.success)return res.status(400).json({error:"Write an update before publishing."});if(!db)return res.status(503).json({error:"Database unavailable"});try{let projectId:string|null=null;if(parsed.data.projectSlug){const rows=await db.execute(sql`SELECT p.id FROM projects p WHERE lower(p.slug)=lower(${parsed.data.projectSlug}) AND (p.owner_id=${req.auth!.subjectId} OR EXISTS(SELECT 1 FROM project_collaborators pc WHERE pc.project_id=p.id AND pc.user_id=${req.auth!.subjectId} AND pc.status='accepted')) LIMIT 1`) as unknown as Array<{id:string}>;if(!rows[0])return res.status(403).json({error:"You can only mention projects where you are an owner or accepted collaborator."});projectId=rows[0].id}const id=randomUUID();const[created]=await db.insert(posts).values({id,authorId:req.auth!.subjectId,body:parsed.data.body,projectId,linkUrl:parsed.data.linkUrl??null,proofOfWorkScore:parsed.data.media.length?"0.7":"0"}).returning();if(parsed.data.media.length)await db.insert(postMedia).values(parsed.data.media.map((media,index)=>({postId:created?.id??id,storagePath:media.path,publicUrl:media.publicUrl,mimeType:media.mimeType,sortOrder:index})));return res.status(201).json({data:{id:created?.id??id,body:parsed.data.body,projectId,projectSlug:parsed.data.projectSlug??null,linkUrl:parsed.data.linkUrl??null,media:parsed.data.media}})}catch(error){console.error("[SocialPostCreate] Failed:",error);return res.status(500).json({error:"Unable to publish this post right now."})}});
